sudo: required 

services:   
  - docker

before_install:
  - docker pull zlog/go-ci

script:
  - docker run -v $GOPATH/src/github.com/noahdesu/go-zlog:/src/go/src/github.com/noahdesu/go-zlog zlog/go-ci
